# Generated by Django 4.2.7 on 2024-01-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_message', models.CharField(max_length=50, verbose_name='тема письма')),
                ('body_message', models.TimeField(blank=True, null=True, verbose_name='тело письма')),
                ('is_active', models.BooleanField(default=True, verbose_name='активация рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение рассылки',
                'verbose_name_plural': 'Сообщения рассылок',
            },
        ),
    ]
