# Generated by Django 4.2.7 on 2024-01-28 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='активация рассылки'),
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время создания рассылки')),
                ('period_choices', models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], max_length=50, verbose_name='период рассылки')),
                ('status_choices', models.CharField(choices=[('ended', 'завершена'), ('created', 'создана'), ('runed', 'запущена')], max_length=50, verbose_name='статус рассылки')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingmessage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Настройки рассылки',
                'verbose_name_plural': 'Настройки рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней рассылки')),
                ('status_try', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], max_length=25, verbose_name='статус попытки')),
                ('answer_serrver', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingmessage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
    ]
