# Generated by Django 4.2.7 on 2024-01-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailingmessage_is_active_mailingsettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='body_message',
            field=models.TextField(blank=True, null=True, verbose_name='тело письма'),
        ),
    ]
