# Generated by Django 4.2.7 on 2024-01-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mailing', '0003_alter_mailingmessage_body_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmessage',
            name='client',
            field=models.ManyToManyField(to='client.client', verbose_name='клиент'),
        ),
    ]
