# Generated by Django 4.2.7 on 2024-02-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mailing', '0005_mailingsettings_end_date_mailingsettings_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='client.client', verbose_name='клиент'),
        ),
    ]
