# Generated by Django 4.2.7 on 2024-02-03 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0007_mailingmessage_owner_alter_mailingmessage_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingsettings',
            old_name='end_date',
            new_name='stop_date',
        ),
        migrations.AlterField(
            model_name='mailinglogs',
            name='status_try',
            field=models.CharField(choices=[('успешно', 'успешно'), ('ошибка', 'ошибка')], max_length=25, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status_choices',
            field=models.CharField(choices=[('created', 'создана'), ('runed', 'запущена'), ('ended', 'завершена')], max_length=50, verbose_name='статус рассылки'),
        ),
    ]
