# Generated by Django 4.2.7 on 2024-02-04 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_rename_end_date_mailingsettings_stop_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglogs',
            old_name='answer_serrver',
            new_name='answer_server',
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='period_choices',
            field=models.CharField(choices=[('day', 'раз в день'), ('week', 'раз в неделю'), ('month', 'раз в месяц')], default='day', max_length=50, verbose_name='период рассылки (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='начало рассылки (по умолчанию)'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status_choices',
            field=models.CharField(choices=[('CREATED', 'создана'), ('RUNING', 'запущена'), ('ENDET', 'завершена')], default='CREATED', max_length=50, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='stop_date',
            field=models.DateField(default=datetime.date.today, verbose_name='конец рассылки (по умолчанию)'),
        ),
    ]
