# Generated by Django 4.2.7 on 2024-02-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_rename_answer_serrver_mailinglogs_answer_server_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingmessage',
            old_name='is_active',
            new_name='is_active_mail',
        ),
    ]
